#!/usr/bin/env python3
"""
Sync tool-owned skills into this marketplace's plugins, as declared in tools.toml.

    python3 scripts/sync_tool_skills.py          # fetch at the pinned refs, write plugins + tools.lock.json
    python3 scripts/sync_tool_skills.py --check  # offline: verify plugins match tools.lock.json and tools.toml

Per tool, `skills`/`skill` (skill directories), `commands` (a directory of
slash-command .md files) and `mcp` (a server launched through bx at the pinned
ref; `bin` names the binary when it is not named after the repo) are each
optional. A top-level `requires_github_token = true` (private marketplaces)
makes the generated SessionStart hook also warn when bx has no GITHUB_TOKEN to
fetch private releases with.

Sources are read from a local checkout (~/dev/projects/<repo>, or $TOOLS_SRC/<repo>) when it
has the pinned ref, otherwise from a shallow clone of github.com/grahambrooks/<repo>.
--check never touches the network; it is what the lint rule runs.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tarfile
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "tools.toml"
LOCK = ROOT / "tools.lock.json"
OWNER = "grahambrooks"
SRC_ROOT = Path(os.environ.get("TOOLS_SRC", Path.home() / "dev" / "projects"))

CHECK_BX = """#!/usr/bin/env bash
# Generated by scripts/sync_tool_skills.py — do not edit.
# This plugin's MCP servers are launched by bx; say so once at session start if it is missing.
if ! command -v bx >/dev/null 2>&1; then
  cat <<'EOF' >&2
[{plugin}] `bx` not found on PATH; its MCP servers ({servers}) will not start.
Install bx:  brew install grahambrooks/bx/bx   (or: cargo install --git https://github.com/grahambrooks/bx)
EOF
fi
{token_check}exit 0
"""

TOKEN_CHECK = """if [ -z "${{GITHUB_TOKEN:-}}" ]; then
  cat <<'EOF' >&2
[{plugin}] GITHUB_TOKEN is not set; bx cannot download these private releases ({servers}).
Export one before starting Claude Code, e.g.  export GITHUB_TOKEN=$(gh auth token)
EOF
fi
"""

HOOKS_JSON = {
    "hooks": {
        "SessionStart": [
            {"hooks": [{"type": "command", "command": "${CLAUDE_PLUGIN_ROOT}/hooks/check-bx.sh"}]}
        ]
    }
}


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_settings() -> dict:
    with MANIFEST.open("rb") as f:
        return tomllib.load(f)


def load_manifest() -> list:
    plugins = load_settings().get("plugin", [])
    for p in plugins:
        for t in p.get("tool", []):
            if "skills" in t and "skill" in t:
                sys.exit(f"tools.toml: {p['name']}/{t['repo']}: set one of `skills` or `skill`, not both")
            if not any(k in t for k in ("skills", "skill", "commands", "mcp")):
                sys.exit(f"tools.toml: {p['name']}/{t['repo']}: provides nothing (no skills, commands or mcp)")
    return plugins


def tool_key(t: dict) -> dict:
    """The manifest fields a lock entry must agree with."""
    return {k: t[k] for k in ("repo", "ref", "skills", "skill", "commands", "mcp") if k in t}


def fetch(repo: str, ref: str, paths: list, dest: Path) -> Path:
    """Materialise `paths` from grahambrooks/<repo> at `ref` under dest; return the checkout root."""
    local = SRC_ROOT / repo
    has_ref = local.is_dir() and subprocess.run(
        ["git", "-C", str(local), "rev-parse", "--verify", "--quiet", f"{ref}^{{commit}}"],
        capture_output=True,
    ).returncode == 0
    if has_ref:
        archive = subprocess.run(
            ["git", "-C", str(local), "archive", "--format=tar", ref, "--", *paths],
            capture_output=True, check=True,
        ).stdout
        tar_path = dest / "src.tar"
        tar_path.write_bytes(archive)
        with tarfile.open(tar_path) as tf:
            tf.extractall(dest / "src", filter="data")
        return dest / "src"
    # SSH, so private repositories clone with the same credentials as a push.
    subprocess.run(
        ["git", "-c", "advice.detachedHead=false", "clone", "--quiet", "--depth", "1", "--branch", ref,
         f"git@github.com:{OWNER}/{repo}.git", str(dest / "src")],
        check=True,
    )
    return dest / "src"


def frontmatter_name(skill_md: Path) -> str:
    m = re.search(r"^---\n(.*?)\n---", skill_md.read_text(), re.S)
    name = m and re.search(r"^name:\s*(.+)$", m.group(1), re.M)
    if not name:
        sys.exit(f"{skill_md}: no `name` in frontmatter")
    return name.group(1).strip().strip("\"'")


def adapt_md(text: str, plugin: str, servers: list, origin: str) -> str:
    """Point allowed-tools at the plugin-scoped MCP tool names and stamp provenance."""
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return text
    front = m.group(1)
    for s in servers:
        front = front.replace(f"mcp__{s}__", f"mcp__plugin_{plugin}_{s}__")
    stamp = f"<!-- Synced from {origin} by scripts/sync_tool_skills.py. Edit upstream, then run `make sync-tools`. -->\n"
    return f"---\n{front}\n---\n{stamp}{text[m.end():]}"


def sync() -> None:
    lock = {"plugins": {}}
    settings = load_settings()
    manifest = load_manifest()
    # A plugin dropped from tools.toml loses its synced files; hand-authored ones stay.
    previous = json.loads(LOCK.read_text()).get("plugins", {}) if LOCK.exists() else {}
    for gone in set(previous) - {p["name"] for p in manifest}:
        for rel in previous[gone]["files"]:
            (ROOT / "plugins" / gone / rel).unlink(missing_ok=True)
        if (ROOT / "plugins" / gone).is_dir():
            prune_empty_dirs(ROOT / "plugins" / gone)
    for plugin in manifest:
        name = plugin["name"]
        pdir = ROOT / "plugins" / name
        tools = plugin.get("tool", [])
        servers = [t["mcp"]["server"] for t in tools if "mcp" in t]
        files: dict[str, bytes] = {}

        for t in tools:
            src_path = t.get("skills") or t.get("skill")
            paths = [p for p in (src_path, t.get("commands")) if p]
            if not paths:
                continue  # MCP only
            with tempfile.TemporaryDirectory() as tmp:
                root = fetch(t["repo"], t["ref"], paths, Path(tmp))
                if "commands" in t:
                    cmds = sorted((root / t["commands"]).glob("*.md"))
                    if not cmds:
                        sys.exit(f"{t['repo']}@{t['ref']}:{t['commands']}: no commands found")
                    for f in cmds:
                        rel = f"commands/{f.name}"
                        if rel in files:
                            sys.exit(f"plugin {name}: two tools both provide {rel}")
                        origin = f"{OWNER}/{t['repo']}@{t['ref']} ({t['commands']}/{f.name})"
                        files[rel] = adapt_md(f.read_text(), name, servers, origin).encode()
                if not src_path:
                    continue
                src = root / src_path
                skill_dirs = [src] if "skill" in t else sorted(d for d in src.iterdir() if (d / "SKILL.md").is_file())
                if not skill_dirs:
                    sys.exit(f"{t['repo']}@{t['ref']}:{src_path}: no skills found")
                for sd in skill_dirs:
                    skill = frontmatter_name(sd / "SKILL.md")
                    origin = f"{OWNER}/{t['repo']}@{t['ref']} ({src_path}{'' if 'skill' in t else '/' + sd.name})"
                    for f in sorted(p for p in sd.rglob("*") if p.is_file()):
                        rel = f"skills/{skill}/{f.relative_to(sd).as_posix()}"
                        if rel in files:
                            sys.exit(f"plugin {name}: two tools both provide {rel}")
                        data = f.read_bytes()
                        if f.name == "SKILL.md":
                            data = adapt_md(data.decode(), name, servers, origin).encode()
                        files[rel] = data

        if servers:
            mcp = {"mcpServers": {
                t["mcp"]["server"]: {
                    "type": "stdio",
                    "command": "bx",
                    "args": [f"{OWNER}/{t['repo']}@{t['ref']}" + (f"#{t['mcp']['bin']}" if t["mcp"].get("bin") else ""),
                             "--", *t["mcp"].get("args", [])],
                }
                for t in tools if "mcp" in t
            }}
            files[".mcp.json"] = (json.dumps(mcp, indent=2) + "\n").encode()
            files["hooks/hooks.json"] = (json.dumps(HOOKS_JSON, indent=2) + "\n").encode()
            listed = ", ".join(servers)
            token_check = TOKEN_CHECK.format(plugin=name, servers=listed) if settings.get("requires_github_token") else ""
            files["hooks/check-bx.sh"] = CHECK_BX.format(plugin=name, servers=listed, token_check=token_check).encode()

        # Replace everything this plugin previously had synced, then write the new set.
        for rel in lock_files(name):
            (pdir / rel).unlink(missing_ok=True)
        for rel, data in files.items():
            out = pdir / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(data)
            if rel.endswith(".sh"):
                out.chmod(0o755)
        prune_empty_dirs(pdir)

        lock["plugins"][name] = {
            "tools": [tool_key(t) for t in tools],
            "files": {rel: sha256(data) for rel, data in sorted(files.items())},
        }
        print(f"synced {name}: {len(files)} files from {', '.join(t['repo'] + '@' + t['ref'] for t in tools)}")

    LOCK.write_text(json.dumps(lock, indent=2, sort_keys=True) + "\n")


def lock_files(plugin: str) -> list:
    if not LOCK.exists():
        return []
    return list(json.loads(LOCK.read_text()).get("plugins", {}).get(plugin, {}).get("files", {}))


def prune_empty_dirs(base: Path) -> None:
    for d in sorted((p for p in base.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True):
        if not any(d.iterdir()):
            d.rmdir()


def check() -> list:
    """Offline consistency check. Returns a list of problems."""
    problems = []
    if not LOCK.exists():
        return ["tools.lock.json is missing. Run 'make sync-tools'."]
    locked = json.loads(LOCK.read_text()).get("plugins", {})
    manifest = {p["name"]: [tool_key(t) for t in p.get("tool", [])] for p in load_manifest()}

    for name in sorted(set(manifest) | set(locked)):
        if name not in locked:
            problems.append(f"plugin {name} is in tools.toml but was never synced. Run 'make sync-tools'.")
            continue
        if name not in manifest:
            problems.append(f"plugin {name} is in tools.lock.json but not tools.toml. Run 'make sync-tools'.")
            continue
        if manifest[name] != locked[name]["tools"]:
            problems.append(f"plugin {name}: tools.toml changed since the last sync. Run 'make sync-tools'.")
        pdir = ROOT / "plugins" / name
        for rel, digest in locked[name]["files"].items():
            f = pdir / rel
            if not f.is_file():
                problems.append(f"plugins/{name}/{rel} is missing. Run 'make sync-tools'.")
            elif sha256(f.read_bytes()) != digest:
                problems.append(f"plugins/{name}/{rel} differs from its synced copy. Edit it upstream, then run 'make sync-tools'.")
        synced_skills = {rel.split("/")[1] for rel in locked[name]["files"] if rel.startswith("skills/")}
        for skill in synced_skills:
            for f in (pdir / "skills" / skill).rglob("*"):
                rel = f.relative_to(pdir).as_posix()
                if f.is_file() and rel not in locked[name]["files"]:
                    problems.append(f"plugins/{name}/{rel} is not from upstream; synced skill directories are replaced on sync.")
    return problems


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify offline instead of syncing")
    args = ap.parse_args()
    if args.check:
        problems = check()
        for p in problems:
            print(p, file=sys.stderr)
        sys.exit(1 if problems else 0)
    sync()


if __name__ == "__main__":
    main()
